version: '3'
services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
      
    ports:
      - 5000:5000
   
    depends_on:
      - mongodb
    environment:
      - MONGO_URI='mongodb+srv://'
  mongodb:
    image: mongo
    
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:


